baseURL = "https://jovial-yonath-8d9e17.netlify.app/"
languageCode = "en-us"
title = "Hi, I'm Kyle"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Kyle Pott"
    description = "Software Engineering"
    githubUsername = "kylepott"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:kylepott@gmail.com.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/kylepott/"
    name = "fab fa-github"
    weight = 2



[[menu.icon]]
    url = "https://www.linkedin.com/in/kylepott/"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://www.goodreads.com/review/list/3470132-kyle?ref=nav_mybooks"
    name = "fab fa-goodreads"
    weight = 4